### ISSUE TITLE
how do i wire this to my Pi

### ISSUE THREAD

**Issue by pigbait** [Hwulex/hyperion-config-switch#5]
how do i wire this from my onkyo 608 to my Pi?

**Comment by Hwulex** [comment]
What do you "wire this to"? There are setup instructions on the main page which should hopefully tell you how to install depending on which operating system you are using with your Pi. If you give me more detail about your specific issue I might be able to help.

https://github.com/Hwulex/hyperion-config-switch/blob/master/README.md

**Comment by Hwulex** [comment]
Closing as over a year old and no response from user. Please re-open if still and issue and need support.
